### ISSUE TITLE
Placebo Crash on Startup, 1.18.1 Custom Modpack

### ISSUE THREAD

**Issue by Poondy** [Shadows-of-Fire/Placebo#36]
Time: 2/4/22, 9:48 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.18.1-39.0.60-universal.jar%23184!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.18.1-39.0.60-universal.jar%23184!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:553) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:409) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:547) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:875) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23180!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.60.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?] {}
-- MOD placebo --
Details:
	Caused by 0: java.lang.RuntimeException: java.lang.ClassNotFoundException: shadows.placebo.util.PlaceboTaskQueue
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:80) ~[javafmllanguage-1.18.1-39.0.60.jar%23182!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.60.jar%23182!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.60.jar%23182!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.60.jar%23181!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: Placebo-1.18.1-6.0.5.jar
	Failure message: Placebo (placebo) has failed to load correctly
		java.lang.RuntimeException: java.lang.ClassNotFoundException: shadows.placebo.util.PlaceboTaskQueue
	Mod Version: 6.0.5
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: shadows.placebo.util.PlaceboTaskQueue
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.60.jar%23182!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.60.jar%23182!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.60.jar%23182!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.60.jar%23181!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2635389048 bytes (2513 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8682
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 17604.72
	Virtual memory used (MB): 12238.09
	Swap memory total (MB): 9495.61
	Swap memory used (MB): 812.05
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseG1GC -Xmx6G -Xms6G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		hexerei-0.1.14.jar                                |Hexerei                       |hexerei                       |0.1.14              |COMMON_SET|Manifest: NOSIGNATURE
		no_null_processors_forge-2.0.2+1.18.1.jar         |No Null Processors            |no_null_processors            |2.0.2+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		Uppers-0.4.0.jar                                  |Uppers                        |uppers                        |0.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |COMMON_SET|Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.1-11.0.1.jar                 |KleeSlabs                     |kleeslabs                     |11.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		Neat 1.8-30.jar                                   |Neat                          |neat                          |1.8-30              |COMMON_SET|Manifest: NOSIGNATURE
		essentials-1.18.1-2.13.3.jar                      |Essentials                    |essentials                    |1.18.1-2.13.3       |COMMON_SET|Manifest: NOSIGNATURE
		glassential-forge-1.18-1.2.1.jar                  |Glassential                   |glassential                   |1.18-1.2.1          |COMMON_SET|Manifest: NOSIGNATURE
		XaerosWorldMap_1.20.2_Forge_1.18.jar              |Xaero's World Map             |xaeroworldmap                 |1.20.2              |COMMON_SET|Manifest: NOSIGNATURE
		CTM-1.18-1.1.3+1.jar                              |ConnectedTexturesMod          |ctm                           |1.18-1.1.3+1        |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.1-11.1.0.jar      |CookingForBlockheads          |cookingforblockheads          |11.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.18.1-6.0.5.jar                          |Placebo                       |placebo                       |6.0.5               |ERROR     |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.16.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.16.0              |COMMON_SET|Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |1.0.0+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		PatinaPipeworks-1.18.1-1.0.6-universal.jar        |Patina Pipeworks              |patinapipeworks               |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.18.1.4.0.jar                     |Guard Villagers               |guardvillagers                |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		twigs-1.1.4-forge.jar                             |Ninni, Dopadream              |twigs                         |1.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		Apotheosis-1.18.1-5.2.2.jar                       |Apotheosis                    |apotheosis                    |5.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		balm-2.4.2+0.jar                                  |Balm                          |balm                          |2.4.2+0             |COMMON_SET|Manifest: NOSIGNATURE
		WaterStrainer-1.18-12.1.0.jar                     |Water Strainer                |waterstrainer                 |1.18-12.1.0         |COMMON_SET|Manifest: NOSIGNATURE
		FpsReducer-forge-1.25-mc1.18.jar                  |FPS Reducer                   |fpsreducer                    |1.25-mc1.18         |COMMON_SET|Manifest: NOSIGNATURE
		carryon-1.18.1-1.17.0.7.jar                       |Carry On                      |carryon                       |1.17.0.7            |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.138.jar         |Just Enough Resources         |jeresources                   |0.13.1.138          |COMMON_SET|Manifest: NOSIGNATURE
		BetterThanMending-1.7.1.jar                       |BetterThanMending             |betterthanmending             |1.7.1               |COMMON_SET|Manifest: NOSIGNATURE
		Paraglider-1.18-1.5.0.0.jar                       |Paraglider                    |paraglider                    |1.5.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		absentbydesign-1.18-1.6.0.jar                     |Absent By Design Mod          |absentbydesign                |1.18-1.6.0          |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		supplementaries-1.18.1-1.1.11.jar                 |Supplementaries               |supplementaries               |1.1.11              |COMMON_SET|Manifest: NOSIGNATURE
		mob_grinding_utils-1.18.1-0.4.33.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.18.1-0.4.33       |COMMON_SET|Manifest: NOSIGNATURE
		Terralith_v2.0.12_Fabric+Forge.jar                |Seed Fix + Terralith          |seedfix_forge                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		PrettyPipes-1.10.5.jar                            |Pretty Pipes                  |prettypipes                   |1.10.5              |COMMON_SET|Manifest: NOSIGNATURE
		AdvancementPlaques-1.18.1-1.4.2.jar               |Advancement Plaques           |advancementplaques            |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		chipped-1.18.1-1.2.1-forge.jar                    |Chipped                       |chipped                       |1.18.1-1.2.1-forge  |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		repurposed_structures_forge-4.2.6+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.2.6+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		horsestatsmod-MC1.18.x-1.4.3.jar                  |Horse Stats Mod               |horsestatsmod                 |1.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		spark-forge.jar                                   |spark                         |spark                         |1.7.2               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.0      |COMMON_SET|Manifest: NOSIGNATURE
		tetra-1.18.1-4.5.0.jar                            |Tetra                         |tetra                         |4.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		relics-0.3.4.1.jar                                |Relics                        |relics                        |0.3.4.1             |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.1-65.jar                           |Patchouli                     |patchouli                     |1.18.1-65           |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.18-0.0.40-ALPHA.jar                     |UI Library Mod                |blockui                       |1.18-0.0.40-ALPHA   |COMMON_SET|Manifest: NOSIGNATURE
		OreExcavation-1.10.160.jar                        |OreExcavation                 |oreexcavation                 |1.10.160            |COMMON_SET|Manifest: NOSIGNATURE
		villagertools-1.18-1.0.2.jar                      |villagertools                 |villagertools                 |1.18-1.0.2          |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Gobber2-Forge-1.18.1-2.6.18.jar                   |Gobber 2                      |gobber2                       |2.6.18              |COMMON_SET|Manifest: NOSIGNATURE
		EnigmaticLegacy-2.14.0.jar                        |Enigmatic Legacy              |enigmaticlegacy               |2.14.0              |COMMON_SET|Manifest: NOSIGNATURE
		buildersaddition-1.18.1-20220123a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.1-20220123a    |COMMON_SET|Manifest: NOSIGNATURE
		sapience-1.18.1-1.0.2.jar                         |Sapience                      |sapience                      |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		AI-Improvements-1.18-0.4.0.jar                    |AI-Improvements               |aiimprovements                |0.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.11.jar                    |GeckoLib                      |geckolib3                     |3.0.11              |COMMON_SET|Manifest: NOSIGNATURE
		effortlessbuilding-1.18.1-2.31.jar                |Effortless Building           |effortlessbuilding            |1.18.1-2.31         |COMMON_SET|Manifest: NOSIGNATURE
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |COMMON_SET|Manifest: NOSIGNATURE
		RootsClassic-1.18.1-1.1.19.jar                    |Roots Classic                 |rootsclassic                  |1.18.1-1.1.19       |COMMON_SET|Manifest: NOSIGNATURE
		Snad-1.18.1-1.21.12.11a.jar                       |Snad                          |snad                          |1.18.1-1.21.12.11a  |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |COMMON_SET|Manifest: NOSIGNATURE
		AttributeFix-Forge-1.18.1-13.0.5.jar              |AttributeFix                  |attributefix                  |13.0.5              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		scannable-1.18.1-forge-1.7.6+da03abb.jar          |Scannable                     |scannable                     |1.7.6               |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.3.jar                  |Waystones                     |waystones                     |9.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.4.jar                     |Clumps                        |clumps                        |8.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.18-5.0.0.1.jar                   |Comforts                      |comforts                      |1.18-5.0.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.4-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.4-forge  |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-1.18.1-4.0.2.jar                        |Artifacts                     |artifacts                     |1.18.1-4.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.18.1-1.5.3.jar             |Simple Storage Network        |storagenetwork                |1.18.1-1.5.3        |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		configured-1.5.1-1.18.1.jar                       |Configured                    |configured                    |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.18.1-9.0.3.jar       |Farming for Blockheads        |farmingforblockheads          |9.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		snuffles-1.0.1.jar                                |Snuffles                      |snuffles                      |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		ExplorersCompass-1.18.1-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.18.1-1.1.2-forge  |COMMON_SET|Manifest: NOSIGNATURE
		azalea-FORGE-3.0.0.jar                            |Better Azalea                 |azalea                        |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		OreBerries-Replanted-1.18.1-0.1.4.3.jar           |Oreberries Replanted          |oreberriesreplanted           |0.1.4.3             |COMMON_SET|Manifest: NOSIGNATURE
		ars_nouveau-1.18.1-2.2.2.jar                      |Ars Nouveau                   |ars_nouveau                   |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.1-39.0.60-universal.jar                |Forge                         |forge                         |39.0.60             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Waddles-1.18-0.8.18.jar                           |Waddles                       |waddles                       |1.18-0.8.18         |COMMON_SET|Manifest: NOSIGNATURE
		selene-1.18-1.12.0.jar                            |Selene                        |selene                        |1.18-1.12.0         |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1      |COMMON_SET|Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		swingthroughgrass-1.18.1-1.8.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.1-1.8.0        |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |COMMON_SET|Manifest: NOSIGNATURE
		domum_ornamentum-1.18.1-1.0.39-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.1-1.0.39-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		easy_villagers-1.18.1-1.0.2.jar                   |Easy Villagers                |easy_villagers                |1.18.1-1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.18.1-1.0.40.jar                         |Iceberg                       |iceberg                       |1.0.40              |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |COMMON_SET|Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.18.1-4.2.0.jar                            |mutil                         |mutil                         |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		LegendaryTooltips-1.18.1-1.2.2.jar                |Legendary Tooltips            |legendarytooltips             |1.2.2}              |COMMON_SET|Manifest: NOSIGNATURE
		ecologics-FORGE-1.18.1-1.1.3.jar                  |Ecologics                     |ecologics                     |1.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.1.3_Forge_1.18.jar              |Xaero's Minimap               |xaerominimap                  |22.1.3              |COMMON_SET|Manifest: NOSIGNATURE
		baubley-heart-canisters-1.18-1.0.0.jar            |Baubley Heart Canisters       |bhc                           |1.18-1.0.0          |COMMON_SET|Manifest: NOSIGNATURE
		malum-1.18.1-1.1.3.jar                            |Malum                         |malum                         |1.18.1-1.1.3        |COMMON_SET|Manifest: NOSIGNATURE
		FastWorkbench-1.18.1-6.0.0.jar                    |Fast Workbench                |fastbench                     |6.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.36.jar                   |Polymorph                     |polymorph                     |1.18.1-0.36         |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |COMMON_SET|Manifest: NOSIGNATURE
		backpacked-2.0.4-1.18.1.jar                       |Backpacked                    |backpacked                    |2.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		structurize-1.18.1-1.0.341-ALPHA.jar              |Structurize                   |structurize                   |1.18.1-1.0.341-ALPHA|COMMON_SET|Manifest: NOSIGNATURE
		multi-piston-1.18-1.2.2-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.18-1.2.2-ALPHA    |COMMON_SET|Manifest: NOSIGNATURE
		minecolonies-1.18.1-1.0.278-RELEASE.jar           |MineColonies                  |minecolonies                  |1.18.1-1.0.278-RELEA|COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.18.1-6.0.1.jar                      |FastFurnace                   |fastfurnace                   |6.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-4.0.0-forge.jar                       |Ferrite Core                  |ferritecore                   |4.0.0               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		connectedglass-1.1.1-mc1.18.jar                   |Connected Glass               |connectedglass                |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		expandability-5.0.0-forge.jar                     |ExpandAbility                 |expandability                 |5.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_core-1.18.1-0.3.2.jar                   |Valhelsia Core                |valhelsia_core                |1.18.1-0.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		forbidden_arcanus-1.18.1-2.0.3.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.18.1-2.0.3        |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 719d9102-c3be-43e4-9661-89aa2753b774
	Flywheel Backend: GL33 Instanced Arrays
	FML: 39.0
	Forge: net.minecraftforge:39.0.60

**Comment by Shadows-of-Fire** [comment]
You have two different placebo jar files loaded

**Comment by Poondy** [comment]
Weird okay, thanks man
