### ISSUE TITLE
Patreon detection, freeze client for 7 minutes

### ISSUE THREAD

**Issue by KuroPeach** [Shadows-of-Fire/Placebo#37]
Patreon detection, freeze client for 7 minutes。

[17:07:08] [Quark Contributor Loading Thread/ERROR] [quark/]: Failed to load patreon information
java.net.SocketTimeoutException: connect timed out
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[?:1.8.0_311] {}
at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:81) ~[?:1.8.0_311] {}
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476) ~[?:1.8.0_311] {}
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218) ~[?:1.8.0_311] {}
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200) ~[?:1.8.0_311] {}
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162) ~[?:1.8.0_311] {}
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394) ~[?:1.8.0_311] {}
at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_311] {}
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:287) ~[?:1.8.0_311] {}
at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_311] {}
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_311] {}
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_311] {}
at sun.net.www.protocol.https.HttpsClient.(HttpsClient.java:292) ~[?:1.8.0_311] {}
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395) ~[?:1.8.0_311] {}
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) ~[?:1.8.0_311] {}
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167) ~[?:1.8.0_311] {}
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061) ~[?:1.8.0_311] {}
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) ~[?:1.8.0_311] {}
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584) ~[?:1.8.0_311] {}
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512) ~[?:1.8.0_311] {}
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_311] {}
at vazkii.quark.base.handler.ContributorRewardHandler$ThreadContributorListLoader.run(ContributorRewardHandler.java:134) [quark:r2.4-321] {re:classloading}
[17:07:19] [Placebo Patreon Wing Loader/ERROR] [placebo/]: Exception loading patreon wing data!
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: java.net.SocketTimeoutException: Read timed out
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at java.net.SocketInputStream.socketRead0(Native Method)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at java.net.SocketInputStream.read(SocketInputStream.java:171)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at java.net.SocketInputStream.read(SocketInputStream.java:141)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at java.net.URL.openStream(URL.java:1092)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at shadows.placebo.patreon.WingsManager.lambda$init$2(WingsManager.java:51)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [STDERR/]: [shadows.placebo.patreon.WingsManager:lambda$init$2:64]: at java.lang.Thread.run(Thread.java:748)
[17:07:19] [Placebo Patreon Wing Loader/INFO] [placebo/]: Loaded 0 patreon wings.
[17:07:22] [Placebo Patreon Trail Loader/ERROR] [placebo/]: Exception loading patreon trails data!
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: java.net.SocketTimeoutException: Read timed out
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at java.net.SocketInputStream.socketRead0(Native Method)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at java.net.SocketInputStream.read(SocketInputStream.java:171)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at java.net.SocketInputStream.read(SocketInputStream.java:141)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:159)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1290)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1199)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at java.net.URL.openStream(URL.java:1092)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at shadows.placebo.patreon.TrailsManager.lambda$init$0(TrailsManager.java:50)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [STDERR/]: [shadows.placebo.patreon.TrailsManager:lambda$init$0:63]: at java.lang.Thread.run(Thread.java:748)
[17:07:22] [Placebo Patreon Trail Loader/INFO] [placebo/]: Loaded 0 patreon trails.
[17:07:40] [Worker-Main-3/INFO] [immersiveengineering/]: Stitching Revolver Textures!
[17:07:40] [Worker-Main-3/INFO] [mo.pi.bl.se.TextureSetup/]: Stitching textures from BlockCarpentry
[17:07:40] [Worker-Main-3/INFO] [mo.pi.bl.se.TextureSetup/]: Stitched all textures from BlockCarpentry
[17:14:07] [Worker-Main-5/INFO] [Emojiful/]: Loaded 1913 emojis
[17:14:11] [Worker-Main-10/INFO] [st.si.SimplyJetpacks/]: Got IMC []
[17:14:11] [Worker-Main-3/INFO] [mo.pi.bl.BlockCarpentryMain/]: Processing InterModCommunication
[17:14:11] [Worker-Main-4/INFO] [co.ha.ti.Tiab/]: Hello world from the MDK
[17:14:11] [Worker-Main-4/INFO] [co.ha.ti.Tiab/]: Got IMC [Hello world]
[17:14:11] [Worker-Main-4/INFO] [ne.bl.mo.cr.CraftingTweaks/]: refinedstorage has registered com.refinedmods.refinedstorage.container.GridContainer for CraftingTweaks
[17:14:11] [Worker-Main-3/INFO] [mo.pi.bl.BlockCarpentryMain/]: Processed InterModCommunication
[17:14:11] [Worker-Main-6/INFO] [mcjtylib/]: Enabled support for The One Probe
[17:14:11] [Worker-Main-6/INFO] [mcjtylib/]: Enabled support for The One Probe
[17:14:11] [Worker-Main-8/INFO] [powah/Config]: Added coolant fluid: minecraft:water, with coldness of: 1 per mb
[17:14:11] [Worker-Main-8/INFO] [powah/Config]: Added block: minecraft:lava, with heat of: 1000
[17:14:11] [Worker-Main-8/INFO] [powah/Config]: Added block: minecraft:magma_block, with heat of: 800
[17:14:11] [Worker-Main-8/INFO] [powah/Config]: Added block: powah:blazing_crystal_block, with heat of: 2800
[17:14:11] [Worker-Main-8/INFO] [powah/Config]: Added fluid: minecraft:lava, with heat of: 10000 per 100 mb
[17:14:11] [Worker-Main-3/INFO] [ne.xa.to.Torchmaster/]: Applying mega torch entity block list overrides...
[17:14:11] [Worker-Main-3/INFO] [ne.xa.to.Torchmaster/]: Applying dread lamp entity block list overrides...
[17:14:11] [Worker-Main-3/INFO] [configured/]: Creating config GUI factories...
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod integratedterminals. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod modnametooltip. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod thermal. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod pitg. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod rftoolsbase. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod xnet. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod powah. Found 0 client config(s) and 15 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod morpheus. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod jeresources. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod toolkit. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mysticalagradditions. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod emojiful. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod betterendforge. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod refinedstorage. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod industrialforegoing. Found 0 client config(s) and 5 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod torchmaster. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod blur. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod botania. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod curios. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod topaddons. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod constructionwand. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod cfm. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod cobblefordays. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod fastleafdecay. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod sdrp. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod aquafied. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod tconplanner. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod miniutilities. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod forgeautofish. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod simplyjetpacks. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod xray. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod jei. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod attributefix. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mekanism. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod invtweaks. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod notenoughwands. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod compactmachines. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod botanypots. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod cofh_core. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod rftoolspower. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod forge. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod integratedcrafting. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod theoneprobe. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod immersiveengineering. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod ding. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod simplelogin. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod rftoolsbuilder. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod jeiintegration. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod pipez. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mantle. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod integrateddynamics. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod ftbbackups. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod gravestone. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod serverconfigupdater. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod integratedterminalscompat. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod harvest. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod structurize. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod appleskin. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod modernui. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod extremesoundmuffler. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod rsrequestify. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod cyclopscore. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod extendedcrafting. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod culinaryconstruct. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod ibicf. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod squatgrow. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-7/WARN] [minecolonies/]: FMLLoadCompleteEvent
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mekanismgenerators. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod xnetgases. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod losttrinkets. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod chocolate. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod farmersdelight. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod commoncapabilities. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod simplybackpacks. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod patchouli. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod rftoolsstorage. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod better_diving. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod blockcarpentry. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod tiab. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod integratedtunnels. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod elevatorid. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mekanismtools. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod aiimprovements. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod bwncr. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod smallships. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod cucumber. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod trashslot. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod appliedenergistics2. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod roadrunner. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod configured. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod charginggadgets. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mcjtylib. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod integrateddynamicscompat. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod toastcontrol. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod akashictome. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod bloodmagic. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod mysticalagriculture. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod craftingtweaks. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod tconstruct. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod rftoolsutility. Found 1 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod titanium. Found 0 client config(s) and 2 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod dimpaintings. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod fluxnetworks. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod ftbteamislands. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod storagedrawers. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod jecharacters. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod seeddrop. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod ftb-power-pots. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod cottonly. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod minecolonies. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod moredragoneggs. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod flowerseeds. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod refinedstorageaddons. Found 0 client config(s) and 0 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod ftbsluice. Found 0 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-3/INFO] [configured/]: Registering config factory for mod chiselsandbits. Found 1 client config(s) and 1 common config(s)
[17:14:11] [Worker-Main-7/WARN] [minecolonies/]: Register mappings
[17:14:12] [Worker-Main-6/INFO] [me.ic.mo.ic.co.iChunUtil/]: Loaded 72 HeadInfo object(s)
[17:14:17] [Render thread/WARN] [minecraft/ClientLanguageMap]: Skipped language file: blockcarpentry:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 28 column 2 path $.advancements.blockcarpentry.gathering.description)
[17:14:17] [Render thread/WARN] [minecraft/ClientLanguageMap]: Skipped language file: integratedtunnels:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 9 column 2 path $.parttype.integratedtunnels.interface_filter_fluid.info)
[17:14:17] [Render thread/WARN] [minecraft/ClientLanguageMap]: Skipped language file: bigreactors:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 706 column 6 path $.api.bigreactors.reactor.tooltip.coil)
[17:14:22] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[17:14:22] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[17:15:06] [Render thread/INFO] [Mystical Agriculture/]: Model replacement took 11 ms
[17:15:08] [Render thread/INFO] [ambientsounds/]: Successfully loaded sound engine. 11 dimension(s) and 32 region(s)
[17:15:09] [Realms Notification Availability checker https://github.com/VazkiiMods/Quark/pull/1/INFO] [mojang/RealmsClient]: Could not authorize you against Realms server: Invalid session id

**Comment by Shadows-of-Fire** [comment]
Both of the placebo patreon loading threads are finished before your 7-min freeze. You have a different issue.

**Comment by KuroPeach** [comment]
Thanks, Maybe Emojiful
