### ISSUE TITLE
Error on Reload

### ISSUE THREAD

**Issue by SkySom** [Shadows-of-Fire/Placebo#5]
Tried to reload some datapacks on a server, got some errors from Placebo
https://gist.github.com/SkySom/59102cd081b5cb98bcd36697aaef6661

```[13Jul2019 01:17:51.736] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_181]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1414) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_193031_aM(MinecraftServer.java:1388) ~[?:?]
	at net.minecraft.command.impl.ReloadCommand.func_198598_a(SourceFile:16) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) [?:?]
	at net.minecraft.command.Commands.func_197059_a(Commands.java:194) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:349) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:325) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableMap.computeIfAbsent(ImmutableMap.java:522) ~[server-1.14.3-extra.jar:?]
	at shadows.placebo.recipe.RecipeHelper.lambda$addRecipes$1(RecipeHelper.java:117) ~[?:2.0.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_181]
	at shadows.placebo.recipe.RecipeHelper.addRecipes(RecipeHelper.java:117) ~[?:2.0.0]
	at shadows.placebo.recipe.RecipeHelper$Reloader.func_195410_a(RecipeHelper.java:161) ~[?:2.0.0]
	at net.minecraft.resources.IResourceManagerReloadListener.lambda$reload$0(IResourceManagerReloadListener.java:16) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1411) ~[?:?]
	... 9 more```

**Comment by Shadows-of-Fire** [comment]
Resolved as of 2.0.1
