### ISSUE TITLE
[1.20.4] Neoforge Clash on launch with Xaero's Maps

### ISSUE THREAD

**Issue by ffuentesm** [Shadows-of-Fire/Placebo#81]
Placebo: 9.2.2
Xaero's World Map: 1.38.4
Neoforge: 20.4.231

Log: https://mclo.gs/q3RlfYB

-- Head --
Thread: Render thread
Stacktrace:
	at xaero.map.events.ClientEvents.handleRenderTick(ClientEvents.java:79) ~[XaerosWorldMap_1.38.4_NeoForge_1.20.4.jar%23383!/:1.38.4] {re:classloading}
	at xaero.map.events.ClientEventsNeoForge.renderTick(ClientEventsNeoForge.java:33) ~[XaerosWorldMap_1.38.4_NeoForge_1.20.4.jar%23383!/:1.38.4] {re:classloading}
	at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%23154!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:351) ~[bus-7.2.0.jar%23154!/:?] {}

**Comment by Shadows-of-Fire** [comment]
I'm not seeing anything related to Placebo in the stack traces, this is purely an issue with Xaero's
